# model config
GAT:
  num_hiddens: 64
  num_layers: 2
  heads: 4
  dropout: 0.5
  concat: True
  jk: last # last, cat, max, lstm,


MLP:
  num_hiddens: 64
  num_layers: 4
  dropout: 0.5
  batch_norm: True


GCN:
  num_hiddens: 64
  num_layers: 2
  dropout: 0.5
  jk: last # last, cat, max, lstm