

meta:
  model_name: GAT
  dataset_name: Cora

model:
  num_hiddens: 64
  num_layers: 2
  heads: 2
  dropout: 0.5
  concat: True
  jk: last # last, cat, max, lstm,

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300

  ckpt_dir: ./ckpt/test_GAT
  gpu: 1

# dataset: