meta:
  model_name: GAT
  dataset_name: ~

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 256
  num_layers: 2
  heads: 4
  dropout: 0.5
  concat: True
  jk: last # last, cat, max, lstm,

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True

  ckpt_dir: ~
  gpu: 0
