# python run_experiments.py -c GAT_flickr.yaml -nc "trainer.gpu=1"

# teacher: The Prediction, Train: 0.5701, Val: 0.5376, Test: 0.5392
meta:
  model_name: GAT
  dataset_name: Flickr
  n_runs: 1
  # seed: 0

model:
  num_hiddens: 256
  num_layers: 2
  heads: 8
  dropout: 0.3

  concat: True
  jk: last # last, cat, max, lstm,
  

trainer:
  lr: 0.005
  weight_decay: 0
  epochs: 500

  verbose: True
  ckpt_dir: ./examples/ckpt/test_GAT
  gpu: 0
