# python run_experiments.py -c GAT_cora.yaml -nc "trainer.gpu=1"

# teacher: the Prediction, Train: 0.9643, Val: 0.8220, Test: 0.8270
meta:
  model_name: GAT
  dataset_name: Cora
  n_runs: 1
  # seed: 0

model:
  num_hiddens: 256
  num_layers: 2
  heads: 8
  dropout: 0.7
  concat: True
  jk: last # last, cat, max, lstm,
  

trainer:
  lr: 0.01
  weight_decay: 0.0001
  epochs: 100
  verbose: True

  ckpt_dir: ./examples/ckpt/test_GAT
  gpu: 1