# python run_experiments.py -c GAT_arxiv.yaml -nc "trainer.gpu=0"
# python run_experiments.py -c GAT_arxiv.yaml -nc "trainer.gpu=0" "model.num_layers=1" "trainer.epochs=100"
# python run_experiments.py -c GAT_arxiv.yaml -nc "trainer.gpu=0" "model.num_layers=2" "trainer.epochs=100"
# python run_experiments.py -c GAT_arxiv.yaml -nc "trainer.gpu=0" "model.num_layers=3" "trainer.epochs=100"

# teacher: dayue 71左右
meta:
  model_name: GAT
  dataset_name: ogbn-arxiv
  n_runs: 1
  # seed: 0

model:
  num_hiddens: 128
  num_layers: 3
  heads: 8
  dropout: 0.3
  norm: bn

  concat: True
  jk: last # last, cat, max, lstm,
  

trainer:
  lr: 0.005
  weight_decay: 0
  epochs: 500

  verbose: True
  ckpt_dir: ./examples/ckpt/test_GAT
  gpu: 0
