# python run_experiments.py -c GCN_pubmed.yaml -nc "trainer.gpu=1"
# The Prediction, Train: 1.0000, Val: 0.7980, Test: 0.7840

meta:
  model_name: GCN
  dataset_name: PubMed
  n_runs: 1

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 128
  num_layers: 2
  dropout: 0.5
  jk: last # last, cat, max, lstm,

trainer:
  lr: 0.01
  weight_decay: 0.0001
  epochs: 500

  verbose: True
  ckpt_dir: ./examples/ckpt/test_GCN
  gpu: 1
