# python run_experiments.py -c GCN_arxiv.yaml -nc "trainer.gpu=1"
# Best Epoch : 344.6667 ± 9.0738
# Best Epoch - Train: 0.7816 ± 0.0011
# Best Epoch - Valid: 0.7267 ± 0.0011
# Best Epoch - Test: 0.7166 ± 0.0024

meta:
  model_name: GCN
  dataset_name: ogbn-arxiv
  n_runs: 3

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 256
  num_layers: 3
  dropout: 0.5
  norm: bn

trainer:
  lr: 0.01
  # weight_decay: !!float 5e-4
  weight_decay: 0
  epochs: 500
  verbose: True

  ckpt_dir: ./examples/ckpt/test_GCN
  gpu: 0
