# python run_experiments.py -c GCN_citeseer.yaml -nc "trainer.gpu=1"
# The Prediction, Train: 0.9417, Val: 0.6900, Test: 0.6820

meta:
  model_name: GCN
  dataset_name: CiteSeer
  n_runs: 1

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 128
  num_layers: 2
  dropout: 0.7
  jk: last # last, cat, max, lstm,

trainer:
  lr: 0.01
  weight_decay: 0
  epochs: 100

  verbose: True
  ckpt_dir: ./examples/ckpt/test_GCN
  gpu: 1
