# python run_experiments.py -c GCN_pubmed.yaml -nc "trainer.gpu=1"
# Best Epoch : 32.8000 ± 2.0494
# Best Epoch - Train: 1.0000 ± 0.0000
# Best Epoch - Valid: 0.8060 ± 0.0014
# Best Epoch - Test: 0.7952 ± 0.0036
meta:
  model_name: GCN
  dataset_name: PubMed
  n_runs: 5

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 256
  num_layers: 2
  dropout: 0.5

trainer:
  lr: 0.01
  weight_decay: !!float 5e-4
  epochs: 100
  verbose: True

  ckpt_dir: ./examples/ckpt/test_GCN
  gpu: 0
