# python run_experiments.py -c GCN_cora.yaml -nc "trainer.gpu=1"
# python run_experiments.py -c GCN_cora.yaml -nc "trainer.gpu=0" "trainer.epochs=500"
# The Prediction, Train: 0.9857, Val: 0.8000, Test: 0.8170

meta:
  model_name: GCN
  dataset_name: Cora
  n_runs: 1

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 128
  num_layers: 2
  dropout: 0.7
  jk: last # last, cat, max, lstm,

trainer:
  lr: 0.01
  weight_decay: !!float 1e-5
  epochs: 50

  verbose: True
  ckpt_dir: ./examples/ckpt/test_GCN
  gpu: 1
