meta:
  model_name: KDModel
  student_name: GAT
  dataset_name: ~

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 256
  num_layers: 2
  heads: 4
  dropout: 0.5
  concat: True
  jk: last

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True
  # ckpt_dir: ./ckpt/test_GAT
  gpu: 0

  kd:
    knowledge_dir: ./examples/ckpt/test_GAT/
    method: soft     # none, soft, hidden, logit
    mask: all     # train_val, train_val_test, all, train_val_unlabeled
    alpha: 0.5
    beta: 1.
    temperature: 20