

meta:
  model_name: KDModel
  student_name: GAT

model:
  num_hiddens: 256
  num_layers: 2
  heads: 4
  dropout: 0.5
  concat: True
  jk: last

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True

  kd:
    knowledge_path: ./ckpt/test_GAT/knowledge.pt
    alpha: 0.8
    temperature: 5

  # ckpt_dir: ./ckpt/test_GAT
  gpu: 0

# dataset:
