# python run_experiments.py -c KDMLP.yaml -nc "trainer.gpu=1" "model.aug.k=0"


meta:
  model_name: KDModel
  student_name: MLP
  dataset_name: Cora
  n_runs: 1

dataset:
  num_features: ~
  num_classes: ~

model:
  num_hiddens: 256
  num_layers: 3
  dropout: 0.5
  batch_norm: True
  aug:
    k: 2
    combine: cat # cat

trainer:
  lr: 0.01
  weight_decay: !!float 5e-4
  epochs: 200
  verbose: True
  # ckpt_dir: ./examples/ckpt/test_GAT
  gpu: 0

  kd:
    knowledge_dir: ./examples/ckpt/Cora_GCN/
    method: soft     # none, soft, hidden, logit, ce_link, soft_link
    mask: train_val_unlabeled     # train_val, train_val_test, all, train_val_unlabeled
    alpha: 1
    beta: 1.
    temperature: 20
    neg_k: 20