

meta:
  model_name: KDModel
  student_name: MLP

model:
  num_hiddens: 64
  num_layers: 4
  dropout: 0.5
  batch_norm: True

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True

  kd:
    softlabel_path: ./ckpt/test_GAT/pred.pt
    alpha: 1
    temperature: 10

  # ckpt_dir: ./ckpt/test_GAT
  gpu: 1

# dataset:
