

meta:
  model_name: KDModel
  student_name: MLP

model:
  num_hiddens: 256
  num_layers: 3
  dropout: 0.5
  batch_norm: True

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True

  kd:
    knowledge_path: ./ckpt/test_GAT/knowledge.pt
    method: feat     # none, soft, feat
    mask: all     # train_val, train_val_test, all
    # alpha: 0.95
    alpha: 1
    beta: 1
    gamma: 1
    temperature: 20

  # ckpt_dir: ./ckpt/test_GAT
  gpu: 0

# dataset:
