meta:
  model_name: MLP

model:
  num_hiddens: 256
  num_layers: 3
  dropout: 0.5
  batch_norm: True

trainer:
  lr: 0.005
  weight_decay: !!float 5e-4
  epochs: 300
  verbose: True

  gpu: 1

# dataset:
