meta:
  teacher: ./examples/GAT.yaml
  # student: ./examples/KDMLP.yaml
  student: ./examples/KDGAT.yaml
  tuner:  ./examples/KDMLP_tuner.yaml
  version: ~
  pipeline_root: ./examples
  gpu: 0
  dataset_name: ~
  stages: ~

student:
  n_runs: 3