meta:
  teacher: ./examples/GAT.yaml
  student: ./examples/KDMLP.yaml
  tuner:  ./examples/KDMLP_tuner.yaml
  version: test_pipeline
  pipeline_root: ./examples
  gpu: 0
  dataset_name: ~
  stages: TS

student:
  n_runs: 3

tuner:
  n_trials: 10
  n_trial_runs: 1