# bash examples/scripts/run_batch.sh > tmp.out
# cat tmp.out | grep "Best Epoch - Test"

# "model.aug_hop=2" "trainer.kd.method='none'" "trainer.epochs=1000" "trainer.lr=0.001"
# "trainer.kd.mask='train_val_unlabeled'"
# "trainer.kd.beta=1" "trainer.kd.alpha=0" 

# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=1" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=2" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=3" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=4" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=5" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=6" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=7" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=8" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=9" "model.dropout=0"
# python run_experiments.py -c SGNN_arxiv.yaml -nc "model.aug_hop=10" "model.dropout=0"


# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=11"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=12"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=13"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=14"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=15"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=16"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=17"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=18"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=19"
# python run_experiments.py -c SGNN_flickr.yaml -nc "model.aug_hop=20"


python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=1"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=2"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=3"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=4"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=5"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=6"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=7"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=8"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=9"   "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=10"  "meta.n_runs=10" 
python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=11"  "meta.n_runs=10" 

# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=1" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc 
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=3" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=4" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=5" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=6" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=7" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=8" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=9" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=10" "trainer.kd.method='none'"
# python run_experiments.py -c KDMLP_cora.yaml -nc "model.aug_hop=11" "trainer.kd.method='none'"